name = "merm"
description = "A soft material-like light and dark theme based on ejmg's zerm theme for Zola"
license = "MIT"
homepage = "https://codeberg.org/papojari/merm"
# The minimum version of Zola required
min_version = "0.8.0"
# An optional live demo URL
demo = "https://papojari.codeberg.page/"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "papojari"
homepage = "https://papojari.codeberg.page"

# If this is porting a theme from another static site engine, provide
# the info of the original author here
[original]
author =  "ejmg"
homepage = "https://github.com/ejmg"
repo = "https://github.com/ejmg/zerm"